name: TinyTunes
description: "TinyTunes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^14.1.1
  connectivity_plus: ^6.0.3
  youtube_player_iframe: ^5.1.2
  flutter_svg: ^2.0.10+1
  device_info_plus: ^10.1.0
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  fluttertoast: ^8.2.5
  supabase_flutter: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audio_service: ^0.18.14
  just_audio: ^0.9.39
  url_launcher: ^6.3.0
  unity_ads_plugin: ^0.3.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/tracks/
    - assets/fonts/
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
          weight: 600
